name: WhatsApp Automation

on:
  workflow_dispatch:

  schedule:
    - cron: '30 6 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python main.py
